name: Node.js CI Test

on:
  pull_request:
    branches: 
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: npm install
    
    - name: Run unit tests
      run: npm run test
    
    # - name: Run end-to-end tests
    #   run: npm run test:e2e
    
    - name: Generate test coverage
      run: npm run test:cov
    
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    