name: Node.js CI Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: evote
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV_SUPABASE }}" > .env
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Run unit tests
        run: npm run test
